### PR TITLE
Initialize the README.md file

### LINKED ISSUE #10: Add README.md
The README should include a captivating description of the tool, along with its logo and instructions to get started with the tool.

### PR DESCRIPTION
**Pull request by boulais01**
# Description

Adds content to the README.md file describing the project and setting up for adding later components.

Fixes #10

## Type of change

- [X] New feature *(non-breaking change which adds functionality)*

# How Has This Been Tested?

- [X] This PR does not need tested

### CODE REVIEW

**Comment by boulais01** [comment]
@simojo @PCain02 Do we think we should open this up for review, merge, and open a new issue for the completion of the TODOs present to provide a basic outline to the repo, or is it better to just wait until the README.md is finished to merge it? I'm happy to keep working on it either way, but I was thinking it might help other contributors to include the guidelines for completion sooner than later.

**Comment by simojo** [comment]
@boulais01 I think we should wait until it's finished. We don't have many more days left on this project anyways, so it shouldn't affect too much. Feel free to do it at your own judgment though.

**Comment by boulais01** [comment]
@PCain02 Once you add the logo we can mark this ready for review

**Comment by PCain02** [comment]
Logo has been added!

**Review by PCain02 — APPROVED** [review]
Looks good to me, we just need to remember to change the `bosco` to `BOSCO` before we present Monday.

**Review by simojo — APPROVED** [review]
LGTM. I see that the `.github/workflows/build.yml` was also added as a part of this PR, but a necessary change nevertheless!

**Pull request merged**
