### PR TITLE
doc: moving how-to readme to root

### PR DESCRIPTION
**Pull request by simojo**
# Description

This PR moves the documentation from `bosco/` into the root that covers how to run the tool.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix *(non-breaking change which fixes an issue)*
- [x] New feature *(non-breaking change which adds functionality)*
- [ ] Breaking change *(fix or feature that would cause existing functionality to
  not work as expected)*
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please briefly write the names of the added tests to test your functionality.

- [x] This PR does not need tested

### CODE REVIEW

**Review by PCain02 — APPROVED** [review]
LGTM!

**Review by PCain02 — CHANGES_REQUESTED** [review]
Oh nevermind the command changed a little bit to look more like this 
`poetry run bosco --starting-size 100 --number-doubles 5 --file bosco/sorting.py --function-name bubble_sort --element-type str` so that needs updated - more specifically I am talking about the example output

**Comment by simojo** [comment]
> Oh nevermind the command changed a little bit to look more like this `poetry run bosco --starting-size 100 --number-doubles 5 --file bosco/sorting.py --function-name bubble_sort --element-type str` so that needs updated - more specifically I am talking about the example output

This is fixed.

**Review by PCain02 — APPROVED** [review]
Thanks for fixing the example!

**Review by AlishChhetri — APPROVED** [review]
Thank you for quickly addressing this change!

**Pull request merged**
